language: bash
services: docker

script:
# DOCKER_USER and $DOCKER_PASS are set in the Travis settings for the project.
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
  - ./build
  - \[ "$TRAVIS_PULL_REQUEST" == "false" ] &&  docker push sqitch/sqitch

after_script:
  - docker images
