language: bash
services: docker

script:
  - ./build

after_script:
  - docker images

# DOCKER_USER and $DOCKER_PASS are set in the Travis settings for the project.
after_success:
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
  - docker push sqitch/sqitch

