name: CI/CD
on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
  schedule:
    - cron: '0 10 25 * *' # Monthly at 10am on the 25th
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./build
  publish:
    name: Push Docker image to Docker Hub
    # Publish v0.9998 when the build job succeeds and it's not a pull request.
    needs: build
    if: github.ref == 'refs/heads/v0.9998' && github.event_name != 'pull_request' && needs.build.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Push to Docker Hub
        # https://github.com/marketplace/actions/publish-docker
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          name: sqitch/sqitch
